### ISSUE TITLE
Use IDX instead of sensor name

### ISSUE THREAD

**Issue by jsiegmund** [allan-gam/ideAlarm#12]
Request; can you make it so we can configure the sensors by ID instead of their name? IDs are much more reliable. When using names it might be nice to have the ability for wildcards. For instance all of my PIR sensors start their name with PIR so I would just configure them as PIR* and automatically include new ones in the setup as well.

**Comment by allan-gam** [comment]
Thanks for your suggestion jsiegmund. I think it would be possible to modify ideAlarm to be able to use the Domoticz idx instead of the device names for sensors but it would need quite some time to rework and it would probably also cause a few breaking changes. When it comes to wildcards for sensor names, it would be even more work and a great part of the logic needs to be rewrited. Anyway, I keep your suggestion in case we have to rewrite a great part of the logic in the future. Thanks.
