### ISSUE TITLE
Please, define optional silent() use on alertDevices

### ISSUE THREAD

**Issue by JRB202** [allan-gam/ideAlarm#13]
Hi,

In config file you declare : 
alertDevices: 
(Elements are Optional) A Lua table containing the named Domoticz devices that shall be automatically switched on during an alert situation.

In ideAlarmModule.lua in line 327 you wrote : 
domoticz.devices(alertDevice).toggleSwitch().silent()

This silent() causes no follow-up events to be triggered

In our case, we declared in ideAlarmConfig.lua in alertDevices field our own virtual switch to trigger our own dzvent chain of event in case of alarm intrusion.

Our virtual switch is well toggled by your code in case of alarm 
but the related dzvent is not executed 
because of silent() function in line 327 which is problem in my logic.

I tried to comment out this function in line 327 as : 
domoticz.devices(alertDevice).toggleSwitch() -- .silent()
and the event related to our virtual switch is executed and I get the behaviour I need which is working perfectly.

So : 
**My suggestion is : 
Add a parameter in config file after alertDevices declaration
to condition the use of this silent() function in ideAlarmModule.lua in line 327**

this is a very easy fix which will offer great extension to ideAlarm

I could even code this for you if you want.

**Comment by JRB202** [comment]
Waiting for your answer, I wrote the update necessary in your code to reach my target and tested it positively.

Please check it and integrate this in your code : 

1) In ideAlarmConfig.lua config file : 
After line : alertDevices={'Siren', 'Garden Lights'},
add this line : 
silentAlertDevices=false, -- If true allow execution of event related to devices listed in alertDevices

So default behavior will be the same as it is today : silent() is used

2) In ideAlarmModule.lua 
at line 327
Replace this line : 
domoticz.devices(alertDevice).toggleSwitch().silent()
by : 
if config.silentAlertDevices then
	domoticz.devices(alertDevice).toggleSwitch().silent()
else
	domoticz.devices(alertDevice).toggleSwitch()
end

That's all !

**Comment by allan-gam** [comment]
Hello @JRB202 Thanks for your suggestions.

I've been thinking about it. 

1. If your alarm device is physical, a siren for example there is a problem if you use it for triggering your own dzvent's chain of event in case of alert situation. If your device gets stolen, gets vandalized, lose it's power source or malfunction in any other way, that chain of events won't just happen. It would make your intruder protection weaker.

2. In general you should be able to test an alarm device without causing an alert situation. Doing it the way you suggested, if you test your device more things would happen that are not related to testing the device itself.

My suggestion is that you instead use [Custom helper functions](https://github.com/allan-gam/ideAlarm/wiki/Event-Helpers) to trigger that chain of events. Please have a look at alarmZoneAlert(domoticz, alarmZone, testMode). By doing that you have not only solved your problem but also removed one possible source of error in your alert event chain.

Another way to do what you wish is to let the virtual text device  "Z1 Status" start your chain of events by scripting. The first method is preferred though because it's logically more related to the alert event itself.

There is also a third alternative that use [Custom helper functions](https://github.com/allan-gam/ideAlarm/wiki/Event-Helpers) to handle your sirens on and off events using your own scriping. Then you also get full control and can pursue your idea to let the change of your siren trigger further actions. But as I said, I think it's a bad alarm design for several reasons.

What do you think about that?

**Comment by JRB202** [comment]
Hi,

Thanks for your quick reply.

You are right with point 1 for physical device.
This have to be explained in doc to recommend to not build chain of alarm event on dzvents attached to physical devices.
The good practice, that is mine, is to use only virtual switch device as alertDevices to trigger attached dzvents alarm chain of event which will be executed in all situations.

For point 2, for me testing the full chain of event is part of a true test process, so no problem here
it just has to be explained in doc.

Regarding your suggestion to use Custom Helper functions, it is technically fine
But as many other users probably
I would prefer to avoid to include part of my code inbeeded in your code in order to be able to upgrade ideAlarm without any impact with your next versions.

All the chain of Alarm event, which is quite complex in my case, must be located in domoticz dzvents with the rest of related code and not in your ideAlarm code, 

With my enhancement we just have to include the virtual switch in ideAlarmConfig.lua file in alertDevices variable and add the line silentAlertDevices=false, which is fine as part of config task.

Then I still recommend to include my enhancement which is so easy to get a significant added value for ideAlarm.

**Comment by allan-gam** [comment]
Thanks.

The custom helper functions are as the name implies "custom" and will never be overwritten by future releases of ideAlarm. You can feel perfectly safe there and it's my recommendation to use it since it allows you to make more complex scripts using all kind of information like what device triggered etc etc. Putting your logic elsewhere makes you much more limited in your scripting.

Anyway, you can of course make the custom functions just switch on/off your own virtual Domoticz alert device and script further actions elsewhere. You could also just script on the change of the virtual Text device named "Z1 Status". Changes upon that device can be triggered upon.

I prefer not to make any changes in the configuration files, not only because it would complicate the configuration (I admit not much in this case), the documentation needs to be extended and all the users of ideAlarm needs to be informed about configuration file changes. The latter is the biggest concern. I don't like the idea that some users are missing optional parameters because it would confuse other users in when they post their configuration on the forum asking for help. So if I follow your suggestion I'd like to to urge everyone else to add it and take a decision on how to set this new value. For you an me, it's obvious that if it's a physical device it's a bad design to trigger further actions upon it in case of an emergency but it will be an educational challenge for me to make all users understand why and some people doesn't always know what happens when they change a parameter (e.g. "We change it and see what happens"). 

;)
