### ISSUE TITLE
Check for open doors etc when arming

### ISSUE THREAD

**Issue by allan-gam** [allan-gam/ideAlarm#2]
When arming, it could be useful to be warned if any doors or windows are opened. Currently this is not implemented. The question is what would we like to happen in such a situation?

**Possible scenarios**
1. When arming from the Domoticz Security Panel (And the Domoticz Security Panel arming mode shall be synced to an ideAlarm zone) and a door is open (E.g. any of the zone's sensors states are "Open" or "On")
2. When arming using the ideAlarm arming toggle buttons  and a door is open (E.g. any of the zone's sensors states are "Open" or "On")

We could call an ideAlarm helper function (if it's defined) that allows the user to be announced in any way about the situation, but then what? Shall we refuse arming or should we go ahead and arm the zone anyway? If we refuse arming and the user didn't observe the warning about open doors the user may walk away in the believe that the zone is armed while it's actually not ... So please think about that and advise me what's the best option here...

**Comment by remb0** [comment]
I Think we must let the users choose.   
I shall use not arming when zone is open.

There are 2 situations: 
-1 you are arming, the wife is already going outside to the car and everything will close in x min.
I first tought to normal arm, with a spoken voice notification, and when the zone is not closed 5 min after arming I want receive high importance notification.
But that's not a solid robust situation.

-2 a window/door is still open,  or a sensor battery is empty.  
then you can arm  but the alarm will make noise because a zone is open.


So I think not arming is the way to go.  speak, notify and flash to warn the user.
better safe then sorry.

**Comment by allan-gam** [comment]
Added config value canArmWithOpenSensors

Will implement something using this ...

**Comment by remb0** [comment]
great issue can be closed :)

**Comment by allan-gam** [comment]
This has now been implemented and documented.
